# Machine Learning Practice

* we are studying numpy library

In [3]:
num_list= [1,4,5,6]
num_list * 4 # output should be [4, 16, 20, 24] 

[1, 4, 5, 6, 1, 4, 5, 6, 1, 4, 5, 6, 1, 4, 5, 6]

In [4]:
import numpy as np
numbers = np.array([1,4,5,6])
numbers * 4

array([ 4, 16, 20, 24])

In [5]:
arr = np.array([1, 5, 7, 8, 9])
arr.size

5

In [6]:
arr.ndim

1

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.shape

(5,)

In [9]:
arr2 = np.array([[4,5,6],[8,10,12]])
arr2.size

6

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr2.size, arr2.ndim, arr2.shape, arr2.dtype

(6, 2, (2, 3), dtype('int64'))

In [14]:
arr2[0]

array([4, 5, 6])

In [15]:
arr2[1]

array([ 8, 10, 12])

* Broadcasting

In [16]:
arr3 = np.array([4, 7, 8, 10, 12]) # operations with list of array
arr3 + arr3

array([ 8, 14, 16, 20, 24])

In [17]:
arr3 * 10

array([ 40,  70,  80, 100, 120])

In [18]:
arr - 1

array([0, 4, 6, 7, 8])

In [19]:
arr/2

array([0.5, 2.5, 3.5, 4. , 4.5])

In [20]:
arr ** 3

array([  1, 125, 343, 512, 729])

In [21]:
list1 = [1, 5, 7] # addition of 2 list
list2 = [10, 11, 13]
list1 + list2

[1, 5, 7, 10, 11, 13]

In [22]:
arr4 = np.ones((3,2)) # It will create a matrix of ones
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
arr5 = np.zeros((3,2)) # It will create a matrix of zeros 
arr5

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
num = np.random.rand() # It will generate a random number from 0 to 1
num

0.9263628383843914

In [25]:
np.random.rand(5) # It will  genereate a five series of numbers from 0 to 1

array([0.83927749, 0.77675979, 0.17007093, 0.16556369, 0.30711906])

In [26]:
np.random.rand(3,2) # It will generate a matrix of 3 by 2 of a series of numver from 0 to 1

array([[0.46148913, 0.21660425],
       [0.41194562, 0.79914382],
       [0.99056713, 0.06490069]])

# randn - genereate a random number from -3 to +3 

In [27]:
np.random.randn()

1.06149660149697

In [28]:
np.random.randn(5)

array([-1.22075584,  0.0985638 , -0.76857538,  0.3428176 , -1.27399877])

In [29]:
np.random.randn(5,5)

array([[ 0.28532459,  1.08951237, -0.80740281,  1.02268695,  0.73332958],
       [-0.36419076,  1.73063811,  0.08980209, -1.76487662, -0.38279056],
       [ 1.258012  ,  1.57177264,  0.67539175, -0.8767528 ,  0.03355131],
       [ 1.36320396, -1.48894888,  0.35713095,  0.54943863, -0.29247025],
       [ 0.26694677, -0.61356715,  0.82756502,  1.15520153, -0.02975555]])

# if we want to standard normal distribution or z-score or scaling that is -3 to +3 then we use randn

# randint - generate a random number from 0 to 100

In [30]:
np.random.randint(100) # from 0 t0 100

25

In [31]:
np.random.randint(50,100) # from 50 t0 100

71

In [32]:
np.random.randint(50,100,5) # from 50 to 100 but five series of numbers

array([95, 93, 69, 51, 99], dtype=int32)

In [33]:
np.random.randint(0,500) # from 0 to 500

431

In [34]:
np.random.randint(10,100,(5,5))  # from 10 to 100 but in a matrix of 5x5

array([[34, 49, 29, 36, 98],
       [24, 34, 79, 25, 42],
       [24, 76, 46, 99, 75],
       [31, 89, 67, 73, 61],
       [80, 30, 31, 16, 46]], dtype=int32)

In [35]:
 #arange -- generates a sequence of numbers - (start,end,step)

In [36]:
np.arange(0,10) # generates a sequence of number from 0 t0 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(20) # default value is 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
np.arange(1,50,2) # step value is 2 means skip one element alternatively after 1st index

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

# reshape function 

In [39]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
# if there are 13 elements to put in a matrix 2D
# 2x6
# 6x2
# 3x4
# 4x3
# 12x1
# 1x12 these are the possible shapes

In [41]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
data = np.arange(0,12).reshape(4,3) # store the matrix in a variable called data

In [43]:
data # calling the data 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
data.max() # maximum value in the matrix

np.int64(11)

In [45]:
data.mean() # mean of the matrix

np.float64(5.5)

In [46]:
data.min()

np.int64(0)

In [47]:
data.std()

np.float64(3.452052529534663)

In [48]:
np.mean(data)

np.float64(5.5)

In [49]:
np.min(data)

np.int64(0)

In [50]:
np.median(data)

np.float64(5.5)

In [51]:
np.std(data)

np.float64(3.452052529534663)

# Filtering the data 

In [52]:
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
data == 7

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

# reshape(-1)

In [54]:
ar = data.reshape(-1) # reshape(-1) converts n dim to 1d data. in this example converted 2d to 1d data
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
ar == 7

array([False, False, False, False, False, False, False,  True, False,
       False, False, False])

In [56]:
ar > 7

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True])

# where function 

In [57]:
np.where(ar ==7)

(array([7]),)

In [58]:
np.where(ar > 5)

(array([ 6,  7,  8,  9, 10, 11]),)

In [59]:
dt = np.array([100,200,300,400,500,600,700])

In [60]:
np.where(dt > 300) # returns the true index value

(array([3, 4, 5, 6]),)

# 2D indexing and slicing 

In [61]:
arr1 = np.array([[40,50,70,10],[20,120,80,90],[70,50,70,100],[170,200,140,140]])
arr1

array([[ 40,  50,  70,  10],
       [ 20, 120,  80,  90],
       [ 70,  50,  70, 100],
       [170, 200, 140, 140]])

In [62]:
arr1[0:2,1:3]

array([[ 50,  70],
       [120,  80]])

In [63]:
arr1[1:,2:]

array([[ 80,  90],
       [ 70, 100],
       [140, 140]])

In [64]:
arr1[:2,:3]

array([[ 40,  50,  70],
       [ 20, 120,  80]])

In [65]:
arr1[::2,::3]

array([[ 40,  10],
       [ 70, 100]])

In [66]:
len(arr1)

4

In [67]:
for i in range(len(arr1)):
    arr1[i] = 100
arr1

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [68]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
len(arr)

4

In [70]:
for i in range(len(arr)):
    arr[i] = 50

In [71]:
arr

array([[50., 50., 50., 50.],
       [50., 50., 50., 50.],
       [50., 50., 50., 50.],
       [50., 50., 50., 50.]])

# 3d array

In [72]:
arr_3d = np.array([[[10,30,40],[50,70,80]],[[11,12,14],[17,19,20]]])
arr_3d

array([[[10, 30, 40],
        [50, 70, 80]],

       [[11, 12, 14],
        [17, 19, 20]]])

In [73]:
arr_3d

array([[[10, 30, 40],
        [50, 70, 80]],

       [[11, 12, 14],
        [17, 19, 20]]])

In [74]:
arr_3d.shape

(2, 2, 3)